package com.bonifasiustrg.learncomposem3.my_soothe_app

import com.bonifasiustrg.learncomposem3.R

object ShootheMockData {
    val alignYourBodyDataLists = listOf(
        ShootheData(
            R.drawable.align_your_body_1,
            R.string.inversions
        ),
        ShootheData(
            R.drawable.align_your_body_2,
            R.string.quick_yoga
        ),
        ShootheData(
            R.drawable.align_your_body_3,
            R.string.tabata
        ),
        ShootheData(
            R.drawable.align_your_body_4,
            R.string.stretching
        ),
        ShootheData(
            R.drawable.align_your_body_5,
            R.string.tabata
        ),
        ShootheData(
            R.drawable.align_your_body_6,
            R.string.nature_meditations
        ),
        ShootheData(
            R.drawable.align_your_body_1,
            R.string.inversions
        ),
        ShootheData(
            R.drawable.align_your_body_2,
            R.string.quick_yoga
        ),
        ShootheData(
            R.drawable.align_your_body_3,
            R.string.tabata
        ),
        ShootheData(
            R.drawable.align_your_body_4,
            R.string.stretching
        ),
        ShootheData(
            R.drawable.align_your_body_5,
            R.string.tabata
        ),
        ShootheData(
            R.drawable.align_your_body_6,
            R.string.nature_meditations
        )
    )
    val favoriteCollectionsDataList = listOf(
        ShootheData(
            R.drawable.align_your_body_1,
            R.string.inversions
        ),
        ShootheData(
            R.drawable.align_your_body_2,
            R.string.quick_yoga
        ),
        ShootheData(
            R.drawable.align_your_body_3,
            R.string.tabata
        ),
        ShootheData(
            R.drawable.align_your_body_4,
            R.string.stretching
        ),
        ShootheData(
            R.drawable.align_your_body_5,
            R.string.tabata
        ),
        ShootheData(
            R.drawable.align_your_body_6,
            R.string.nature_meditations
        ),
        ShootheData(
            R.drawable.align_your_body_1,
            R.string.inversions
        ),
        ShootheData(
            R.drawable.align_your_body_2,
            R.string.quick_yoga
        ),
        ShootheData(
            R.drawable.align_your_body_3,
            R.string.tabata
        ),
        ShootheData(
            R.drawable.align_your_body_4,
            R.string.stretching
        ),
        ShootheData(
            R.drawable.align_your_body_5,
            R.string.tabata
        ),
        ShootheData(
            R.drawable.align_your_body_6,
            R.string.nature_meditations
        )
    )
}